### ISSUE TITLE
Clarification: How do you send System messages to the Assistant?

### ISSUE THREAD

**Issue by TobiasLorek** [tyler-dodge/org-assistant#10]
Hi, Really cool plugin!

One thing that I dont get is how you send system messages to the assistant.
e.g. 
```json
{
  "messages": [
    {
      "role": "system",
      "content": "Act as an elisp developer"
    } 
 ]
}
```
You write something about example blocks before any user input being interpreted as system messages, is this what you are referring to?

Does that include ALL example blocks not following a src block?

**Comment by tyler-dodge** [comment]
Here's an example of how it works. As soon as there is a src block in a given heading, the example blocks become responses from the endpoint currently. I'm thinking of changing it so that the responses from the AI are also src blocks, which would then make it so all example blocks are system blocks instead.

```
* Prior Top Level Headline
#+BEGIN_EXAMPLE
System Message Ignored since before Top Level headline
#+END_EXAMPLE
* Top Level Headline
#+BEGIN_EXAMPLE
System message used since after top level headline
#+END_EXAMPLE

#+BEGIN_SRC assistant :echo
User message after headline
#+END_SRC

#+BEGIN_EXAMPLE
System message used since after top level headline
#+END_EXAMPLE

#+BEGIN_SRC assistant :echo
Second user message
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
(system . "System message used since after top level headline")
(user . "User message after headline")
(assistant . "System message used since after top level headline")
(user . "Second user message")
#+END_EXAMPLE
```

**Comment by TobiasLorek** [comment]
Thanks for clarifying!
