### ISSUE TITLE
Confusing error on curl version <7.82.0: "exited abnormally with code 2"

### ISSUE THREAD

**Issue by spenczar** [tyler-dodge/org-assistant#11]
org-assistant generates a curl command that looks like this:
```
curl https://api.openai.com/v1/chat/completions \
  -H 'Authorization:Bearer <REDACTED>' \
  -H 'Content-Type:application/json; charset=utf-8' \
  -X POST \
  --json @/var/folders/kg/jqdn2j5s4n3f4y9_1swlftrm0000gn/T/jsonsZglKi
```

The `--json` argument was added in v7.82.0 from March 5, 2022 (https://curl.se/mail/lib-2022-03/0011.html).

If the local version of curl predates that, you get a very confusing output:

```
* Question
#+BEGIN_SRC ?
hi
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
(error "exited abnormally with code 2
")
#+END_EXAMPLE

#+BEGIN_SRC ?

#+END_SRC
```

(this is with curl 7.79.1 from 2021-09-22)

It turns out that replacing `--json` with `--data` (no other changes!) works on my version of curl, 7.79.1, since the curl command is already setting the content-type header. So changing the command to call --data might be an easy fix to be compatible with older curl versions. Of course, upgrading cURL is what I'll do in the short term :)

**Comment by tyler-dodge** [comment]
Makes sense, thanks for bringing this to my attention, I'll go ahead and switch to using --data because --json is not worth the compatibility tradeoff (easy enough to add the application/json header manually).
