### ISSUE TITLE
system prompt and tuning parameters

### ISSUE THREAD

**Issue by titaniumbones** [tyler-dodge/org-assistant#13]
Thanks for this package; the approach to iteration is really interesting and helpful for exploration.  Something I miss from org-ai is the ability to set the system-prompt and to tune the model manually.  Do you have plans to add defcustoms for these parameters?  Just wondering.  Thanks again.

**Comment by tyler-dodge** [comment]
I'm glad to hear you are finding it useful!

I'm planning on adding the model tuning parameters soon, and that makes sense to have it be a defcustom. It'll probably be a plist that contains gets added directly to the request, so it won't require a code change here to adapt as these APIs change.

I think the usecase you are talking about for system on the other hand is supported already via:

```
* Top Level Headline
#+BEGIN_EXAMPLE
System Prompt
#+END_EXAMPLE

#+BEGIN_SRC assistant
Hi
#+END_SRC
```

Any example block before the first src block is treated as a system prompt

**Comment by tyler-dodge** [comment]
Tuning is now possible via the :params argument

```
#+BEGIN_SRC assistant :params '((frequency_penalty . 1.0))
#+END_SRC
```

There's also now the `org-assistant-chat-extra-parameters-alist` as well for setting that globally.

Also, responses from the AI are now SRC blocks as well. So, you can specify who is sending a given block with the argument :sender

```

#+BEGIN_SRC assistant :sender assistant :params '((frequency_penalty . 1.0))
#+END_SRC
```

The other options that work for that are `system`, `assistant`, and `user`.

Closing this out for now, but feel free to re-open if you have any questions
