### ISSUE TITLE
Preview what will be sent to API

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#15]
When I have long branching trees of AI conversations, it can be difficult to grasp what exactly will be sent to the API. Especially if you add in noweb into the mix.

It would be useful if there was a way to preview exactly what will be sent, along with what users will send each message.

I have made a small function below that shows me what has been sent to the API, after its already been sent.
```
(defvar my/org-assistant-debug-buf nil)
(defvar my/org-assistant-debug-buf-name "*org-assistant-debug-buf*")

(defun my/org-assistant-debug-buffer-get ()
  (or (and (buffer-live-p my/org-assistant-debug-buf) my/org-assistant-debug-buf)
      (with-current-buffer (generate-new-buffer my/org-assistant-debug-buf-name)
        (setq my/org-assistant-debug-buf (current-buffer))
        (visual-line-mode)
        (current-buffer))))

(defun my/org-assistant-format (blocks)
  (->> blocks
       (--map (list
               (cons "content" (cdr it))
               (cons "role" (symbol-name (car it)))))
       (vconcat)))

(defun my/org-assistant--debug (fun &rest args)
  (let ((res (funcall fun args)))
    (with-current-buffer (my/org-assistant-debug-buffer-get)
      (erase-buffer)
      (insert
       (format "%S"
               (my/org-assistant-format res)
               )))
    res))

(advice-add #'org-assistant--org-blocks :around #'my/org-assistant--debug)
```

The UI isn't great, it would be better if the different messages were more clearly distinguished.

**Comment by tyler-dodge** [comment]
In a recent update I added the :echo argument, which I think does what you want

If you add it to any conversation block, it'll output the conversation that would be sent instead of actually sending it. 

```
#+BEGIN_SRC ? :echo
Hi
#+END_SRC

#+BEGIN_EXAMPLE
(user . "Hi")
#+END_EXAMPLE
```

Feel free to reopen if you had something else in mind

**Comment by walseb** [comment]
That's excellent! I will have a look!

Although I think my implementation has some advantages in that you can find out what was sent even if you forgot to first run a block with the echo setting.

Perhaps a request logging setting for org-assistant would be appropriate. It could show a log of all communication between org-assistant and the AI API, akin to the messages buffer in emacs.

**Comment by tyler-dodge** [comment]
Yeah, a request logging buffer makes sense to me.  I'll probably have it behind a defcustom flag.
