### ISSUE TITLE
Streaming output

### ISSUE THREAD

**Issue by spenczar** [tyler-dodge/org-assistant#17]
gpt-4 is very slow to generate large output, which is painful when using org-assistant. It can take a few minutes to receive a full response - but you get no feedback, just waiting.

ChatGPT supports streaming output to help with this. org-assistant could stream results and write into the buffer one token at a time.

Turning on the behavior for the API is easy; the hard part is parsing the results and handling them token-by-token. To enable the API, the client would need to set `"stream": true` (at the top level of the JSON payload, next to `"model": "gpt-3.5-turbo"` for example). Curl would need to be invoked with `--no-buffer` to avoid any internal buffering. 

Then, the SSE stream would need to be parsed and each datagram would need to be handled. The SSE spec is relatively simple: data messages are sent as lines prefixed with`data:`. A blank line separates data messages. In the OpenAI implementation, each data message is either a JSON object which describes a single token to insert, or the exact string "[DONE]" to indicate termination.

I think handling the SSE stream would require a change in org-assistant's implementation away from using `set-process-sentinel`, which fires just once when the curl process exits, to using `accept-process-output` to do incremental reads from stdout. It could get hairy, I'm not sure.

Here is an example of what the curl output looks like, for reference, when streaming:
```
$ curl https://api.openai.com/v1/chat/completions -H 'Authorization:Bearer <REDACTED>' -H 'Content-Type:application/json; charset=utf-8' -X POST --data @./gpt4.json --no-buffer
data: {"id":"chatcmpl-7CZ5sgsMjO6HZuAgFDj2AZEb1ZfIG","object":"chat.completion.chunk","created":1683229192,"model":"gpt-4-0314","choices":[{"delta":{"role":"assistant"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7CZ5sgsMjO6HZuAgFDj2AZEb1ZfIG","object":"chat.completion.chunk","created":1683229192,"model":"gpt-4-0314","choices":[{"delta":{"content":"I"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7CZ5sgsMjO6HZuAgFDj2AZEb1ZfIG","object":"chat.completion.chunk","created":1683229192,"model":"gpt-4-0314","choices":[{"delta":{"content":" am"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7CZ5sgsMjO6HZuAgFDj2AZEb1ZfIG","object":"chat.completion.chunk","created":1683229192,"model":"gpt-4-0314","choices":[{"delta":{"content":" powered"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7CZ5sgsMjO6HZuAgFDj2AZEb1ZfIG","object":"chat.completion.chunk","created":1683229192,"model":"gpt-4-0314","choices":[{"delta":{"content":" by"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7CZ5sgsMjO6HZuAgFDj2AZEb1ZfIG","object":"chat.completion.chunk","created":1683229192,"model":"gpt-4-0314","choices":[{"delta":{"content":" Open"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7CZ5sgsMjO6HZuAgFDj2AZEb1ZfIG","object":"chat.completion.chunk","created":1683229192,"model":"gpt-4-0314","choices":[{"delta":{"content":"AI"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7CZ5sgsMjO6HZuAgFDj2AZEb1ZfIG","object":"chat.completion.chunk","created":1683229192,"model":"gpt-4-0314","choices":[{"delta":{"content":"'s"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7CZ5sgsMjO6HZuAgFDj2AZEb1ZfIG","object":"chat.completion.chunk","created":1683229192,"model":"gpt-4-0314","choices":[{"delta":{"content":" G"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7CZ5sgsMjO6HZuAgFDj2AZEb1ZfIG","object":"chat.completion.chunk","created":1683229192,"model":"gpt-4-0314","choices":[{"delta":{"content":"PT"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7CZ5sgsMjO6HZuAgFDj2AZEb1ZfIG","object":"chat.completion.chunk","created":1683229192,"model":"gpt-4-0314","choices":[{"delta":{"content":"-"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7CZ5sgsMjO6HZuAgFDj2AZEb1ZfIG","object":"chat.completion.chunk","created":1683229192,"model":"gpt-4-0314","choices":[{"delta":{"content":"3"},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7CZ5sgsMjO6HZuAgFDj2AZEb1ZfIG","object":"chat.completion.chunk","created":1683229192,"model":"gpt-4-0314","choices":[{"delta":{"content":"."},"index":0,"finish_reason":null}]}

data: {"id":"chatcmpl-7CZ5sgsMjO6HZuAgFDj2AZEb1ZfIG","object":"chat.completion.chunk","created":1683229192,"model":"gpt-4-0314","choices":[{"delta":{},"index":0,"finish_reason":"stop"}]}

data: [DONE]
```

**Comment by tyler-dodge** [comment]
I think that's a worthwhile change.

Yeah, I'll need to switch to using a process-filter instead of the sentinel, but it's not too difficult of a change / something I've done before. I'm using the sentinel now just because it was easier for a v1 release. The process-filter gets called whenever the process sends any output, so that'll make it much nicer.

I could see myself finding time in the next week or so to get that implemented, possibly earlier if my initial implementation goes smoothly.

**Comment by tyler-dodge** [comment]
Ended up getting the urge to implement it, so got an initial implementation here:

 https://github.com/tyler-dodge/org-assistant/tree/streaming

There are probably bugs with this commit, and the image generation is definitely broken, but streaming works.

**Comment by spenczar** [comment]
Hot damn! That was quick! I'll give it a shot.

**Comment by spenczar** [comment]
Just letting you know that branch is working great for me (at commit 25983fa709a2fd2ab6adc1144f100d22629fcdf9, which is the current HEAD of the streaming branch). All I do is text prompting, but it's perfect for working with gpt-4.

**Comment by tyler-dodge** [comment]
Good to note / makes sense to me, I'll make that change sometime soon.

**Comment by tyler-dodge** [comment]
Cancellation should work as expected now. Also, merged the streaming branch into main, so closing this out.
