### ISSUE TITLE
Cancel all tasks

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#18]
Is there a way to cancel all running tasks?

Sometimes I have started many and delete the buffer they are running in, for instance, meaning that all tasks will be run, but trigger errors as they are completed one by one. 

Relating to that, it would make sense to add the cancel all tasks function to the kill-buffer hook of the buffer you run it in.

**Comment by tyler-dodge** [comment]
The kill buffer hook sounds worthwhile to me

`org-assistant-clear-request-queue` is the command currently, although it does not kill the processes on the main branch currently.

**Comment by tyler-dodge** [comment]
Implemented with: https://github.com/tyler-dodge/org-assistant/commit/5444595dd64aeafa7cd708497ade709d23e6d186
