### ISSUE TITLE
Enable markdown mode by default?

### ISSUE THREAD

**Issue by spenczar** [tyler-dodge/org-assistant#19]
org-assisnant's source code blocks are not associated with any particular major mode, currently. That can be changed, though. I have this in my `init.el`:

```elisp
(add-to-list 'org-src-lang-modes '("?" . markdown))
(add-to-list 'org-src-lang-modes '("assistant" . markdown))
```

This makes it so that I'm using markdown-mode when within the block. This has a bunch of nice effects, but a very nice one is fontification. When combined with `(setq markdown-fontify-code-blocks-natively t)`, this gets very nice indeed:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/880413/236520029-41e3bb51-60f0-4ade-8959-d12c9922f80c.png">

---

I can see arguments against this:
 - `markdown-mode` is, incredibly, not bundled into Emacs. Maybe there is some mailing list thread about this, I don't know. But this would add a dependency, anyway.
 - Isn't org better than markdown? Well, yes, but ChatGPT is pretty bad at responding in properly-formatted org text, and also nested org-within-org is horrible to write, so prompting in markdown is a lot easier.
 - The configuration is pretty easy to do as a user, although it took some hunting to figure out exactly the right way to specify it.

But it's so pleasant to work with, that maybe that outweighs the costs. Or maybe just document it? I don't know - up to you.

**Comment by tyler-dodge** [comment]
Thanks for this, I did not know how to do this with org babel offhand, so that is helpful to me.

I added an `org-assistant-setup` function for these kind of optional changes that you may want to override like modifying the `org-src-lang-modes` .

https://github.com/tyler-dodge/org-assistant/commit/ad5384659500ec683fb80c87c07e16bce15b5fb4
