### ISSUE TITLE
noweb support

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#2]
It appears that noweb isn't supported when running the blocks. 

What's more, the text block named 'example' here gets sent to OpenAI when you put it above the prompt, which can be a problem. Maybe there should be a way to designate blocks to not be included in the request?

```
#+NAME: bar
#+BEGIN_SRC text
foo
#+END_SRC

#+BEGIN_SRC assistant :noweb yes
Read back to me the following text:
<<bar>>
#+END_SRC
```

**Comment by tyler-dodge** [comment]
Thanks for the bug report.

Ah that makes sense, yeah there must be a bug with collecting the source blocks where it includes non-assistant blocks incorrectly. I'll take a look into that and fix it.

Adding noweb support makes sense to me, so I'll do that soon as well.

**Comment by walseb** [comment]
Thank you!

I fixed the issue with the src block being included temporarily by adding a check in `org-assistant--org-blocks` to see whether the src block has a name, and if so discard it:
```emacs-lisp
...
                                        (min start-pt range-end) t)
               collect (progn
                         ;; I added this:
                         (unless
                             (save-excursion
                               (goto-char (match-beginning 0))
                               (ignore-errors
                                 (org-element-property :name (org-element-context))))
                           (let* ((match-start (match-beginning 0))
                                  (match-end (match-end 0))
                                  (message-type
                                   (progn
                                     (goto-char match-start)
                                     (let ((line (thing-at-point 'line)))
                                       (if (s-contains-p "BEGIN_EXAMPLE" line)
                                           (if (save-excursion
                                                 (forward-line -1)
...
```

**Comment by tyler-dodge** [comment]
Thanks for that. I ended up filtering it out in a slightly different spot in this commit: https://github.com/tyler-dodge/org-assistant/commit/a0796cfc5321f097f34c5b6215814e7bb54173cb

Still going to make the noweb integration implementation, so leaving this issue open until that's done.

**Comment by tyler-dodge** [comment]
https://github.com/tyler-dodge/org-assistant/commit/2786270c6876619967e16d6afdce074ddc7870fe

Added noweb support with this commit, so closing this issue out.

**Comment by walseb** [comment]
Thank you so much! 

Noweb templates work perfectly now.
