### ISSUE TITLE
org-assistant-response-completed-hook should be called with text and prompt ID as arguments

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#20]
`org-assistant-response-completed-hook` currently just sets and restores the cursor position, I believe.

It would be useful if it was instead run with `run-hook-with-args` and supplied with the text and the ID for the prompt that was just pasted.

That way, one could easily set up notifications that contain the message that was just generated.

**Comment by tyler-dodge** [comment]
Makes sense to me, this should be working as expected after this commit: https://github.com/tyler-dodge/org-assistant/commit/c104763fb81ad5b55294038fc3c32f47547ed188
