### ISSUE TITLE
Streaming id location

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#21]
Hello!

I have been trying out the streaming branch, and it's excellent so far.

One minor issue I have with it is that it puts the ID of the block that's being streamed in at the end of the source block, inside the contents.

It might be better to put it inside the SRC header line, so it's not present in the contents.

That would make it easier to copy the text while it's being streamed in, especially when using functions that copy the entire block contents, excluding the header arguments and such.

For instance, it could look something like this:

```
#+BEGIN_SRC assistant :sender assistant :stream-id ...
```

The block id would then be removed when the stream is completed, just as it is at the moment.

Perhaps there are some downsides to this. Thoughts?

**Comment by walseb** [comment]
It occurred to me that it might be much safer to put the ID in the header, in case the AI API returns a UUID that may be confused with the UUID used to identify where to put the streamed in content.

This wouldn't be an issue if the UUID was in the header, since the header can't be written to by any AI API.

**Comment by tyler-dodge** [comment]
Switched out to using the stream-id in the header, I think it's better, but was a less direct implementation from the non-streaming implementation.

https://github.com/tyler-dodge/org-assistant/commit/98033328e4f84b52539a9f0b5f0887c2ce2b8cae

**Comment by walseb** [comment]
That's great, thank you!
