### ISSUE TITLE
Evaluating thread while streaming

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#23]
Currently, when evaluating blocks that require a parent assistant block that's incomplete and being currently streamed in, the block isn't delayed until all parent blocks in the conversation are finished. Instead, it takes what has been streamed in at the moment of evaluation and sends that to the AI API.

It would make more sense if child blocks waited until all parent blocks were streamed in fully.

Perhaps having this check would be easier if the streaming status was present in the org block src header line, in case the conversation is regarding UUIDs, which might be mistaken for the UUID being used to stream in the content. Ref: https://github.com/tyler-dodge/org-assistant/issues/21.

Here's an example where I evaluate the child block before the parent block finishes, leading to an inaccurate reply of '272 words'.
```
#+BEGIN_SRC assistant
Write me a 500 word poem about emacs
#+END_SRC

#+RESULTS:
#+BEGIN_SRC assistant :sender assistant
In the world of text editors, few can compare
To the power and flexibility of Emacs software
It's a tool that's been crafted with care
And with each release, it becomes more rare

It's a program that's been written in Lisp
And it's often used to write a script
For those who prefer to work in a terminal
Emacs is the editor that's truly indispensable

It's not just for coding
a956aadf-9939-4f58-81d6-220c35925e5b
#+END_SRC


#+BEGIN_SRC assistant
How many words is the poem you just wrote?
#+END_SRC

#+RESULTS:
#+BEGIN_SRC assistant :sender assistant
272 words.
#+END_SRC

```

**Comment by tyler-dodge** [comment]
Yeah, that makes sense to me / I plan on implementing it this way.

**Comment by tyler-dodge** [comment]
With this change: https://github.com/tyler-dodge/org-assistant/commit/3a89386c507a335c0b65fe9018c14c11e864b37d

the messages are populated when sending the request instead of when you run Ctrl-C Ctrl-C, so if you are using parallelism set to 1, it'll effectively work how you're describing.

**Comment by tyler-dodge** [comment]
Closing out for now since I do not intend to implement dependency resolution for src block evaluation at this time, and I think this implementation gets most of the value add.

**Comment by walseb** [comment]
Good idea! Thanks!
