### ISSUE TITLE
Evaluating a block that's currently streaming

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#25]
Hello again!

Evaluating a block that's currently being streamed in causes a bunch of errors to be printed.

**Comment by tyler-dodge** [comment]
This was caused by cancelling blocks before point while evaluating a block. Switching to only cancelling blocks after point because it'll be less confusing: https://github.com/tyler-dodge/org-assistant/commit/0c1d9916c5fc763b4dad2449c467bef0f4ead889

**Comment by walseb** [comment]
Thanks!
