### ISSUE TITLE
Too much is escaped

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#26]
Hello!

It appears that all star characters that are printed gets escaped with a comma.

However, only stars at BOL should be escaped, as those are the only ones that could be org syntax.

Example:
```
#+BEGIN_SRC assistant
Give me examples of the markdown star character in use
#+END_SRC

#+RESULTS:
#+BEGIN_SRC assistant :sender assistant
1. Emphasis: `_This text will be italicized_.`
2. Strong emphasis: `,**This text will be bold,**`.
3. Strikethrough: `~~This text will be crossed out~~`.
4. Unordered list:
```

See that `*` gets escaped as `,*`, thereby breaking Markdown syntax even if you were to enter the block.

**Comment by tyler-dodge** [comment]
Should be fixed with: https://github.com/tyler-dodge/org-assistant/commit/219d8e38e8f80006f0065bbe1dd81c9d5078be33

**Comment by walseb** [comment]
Thank you!
