### ISSUE TITLE
Accessing text field while it's being streamed in

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#30]
Hello!

The overlays for streaming are working brilliantly so far, however, due to the way overlays work, the cursor can't enter them, and so text can't be copied while content is being streamed in.

I wonder if there are any overlay properties that can be set to allow this, but I doubt it, as I believe overlays occupy a single character in the buffer.

Thoughts?

**Comment by walseb** [comment]
A band aid on this issue could be to provide a bind that copies whatever text is in the overlay that's currently being streamed in.

Or perhaps, opening up a block that's being screamed in with org-toggle-src could show the text without its overlay, allowing you to copy anything in the buffer, but that sounds complicated, especially if the user were to save that src buffer mid-stream.

**Comment by tyler-dodge** [comment]
Yeah, I think the way I'll end up going with it is adding a function that'll copy the contents into the kill ring, since yeah, the other ways do sound like they're going to be very complicated.

It'll probably be at least a week before I allocate any time to this.

**Comment by tyler-dodge** [comment]
Added the interactive `org-assistant-yank-block` for yanking the block at point in https://github.com/tyler-dodge/org-assistant/commit/c572c1a2f63fc8e05b8ff8ef4bc8956ff89edff9

**Comment by walseb** [comment]
Thank you!
