### ISSUE TITLE
Bug related to freezing prompt & cancelling blocks

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#31]
Hello!

Sometimes when I use this package on an unreliable network, the prompt will simply freeze without explanation.

What's more, when I execute the block again, the overlay jumps up to the character at the start of the org block and stays there while a new prompt is created below. Usually when this happens, the new overlay will freeze as well, and the only way to fix it is to kill the buffer.

I'm not sure how to debug this issue. Perhaps there should be an interactive function that displays all the relevant state and pretty prints them for bug reports and diagnostics.

Here's an image of one of my src blocks experiencing the issue:
![org-assistant](https://github.com/tyler-dodge/org-assistant/assets/2865774/4b96a63c-5633-4563-81b5-c17252d96062)

The _ before the src block is the original overlay. The reason why it doesn't say BEGIN_SRC is because I'm hiding that part through `org-modern`

**Comment by walseb** [comment]
I have another similar issue now where the prompt fails silently and cancels the task. I'm not sure what the issue is. I do have an internet connection and the in flight list is empty 0 when I initiate the request. Killing and re-opening the buffer doesn't help.

**Comment by walseb** [comment]
When intercepting `org-assistant--org-blocks`, I see that it returns an empty list, so I don't think it's a network error. The However, the issue is gone now, and I didn't get time to go further with debugging it. I will try again when it occurs next time.

**Comment by walseb** [comment]
Found it, that bug is due to my src being indented. I didn't see it because org-modern hides any indentation to an SRC block. Ref https://github.com/tyler-dodge/org-assistant/issues/32.

**Comment by tyler-dodge** [comment]
Fixed with https://github.com/tyler-dodge/org-assistant/commit/0fb0342e24b2f928612ed0fd2d551080eac700fe
