### ISSUE TITLE
Doesn't support indented org blocks

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#32]
Hello!

Currently, org-assistant fails silently if the src block is indented. Examples:

Fails:
```
   #+BEGIN_SRC assistant
   foo
   #+END_SRC
```

Works:
```
#+BEGIN_SRC assistant
bar
#+END_SRC
```

I think having indented SRC blocks is valid org syntax. The view src bind still works on them, exporting them works, and they even get the text indented to match the indent of the block whenever you exit their src edit mode.

The reason why I ran into this issue is because I'm using org-modern, and it doesn't display any leading spaces in src blocks. Org-assistant failed silently on those blocks because they had that leading space.

Thoughts?

Thanks!

**Comment by tyler-dodge** [comment]
Fixed with https://github.com/tyler-dodge/org-assistant/commit/0fb0342e24b2f928612ed0fd2d551080eac700fe
