### ISSUE TITLE
/tmp memory leak

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#34]
Hello!

It appears that `org-assistant` creates temp files but doesn't clean them up afterwards. See https://github.com/tyler-dodge/org-assistant/blob/main/org-assistant.el#696

I believe the /tmp directory usually gets cleared out after every restart, but it would be neater to have them be removed before then.

Is there an easy way to have them be removed after they aren't needed anymore?

**Comment by tyler-dodge** [comment]
Fixed with https://github.com/tyler-dodge/org-assistant/commit/85977c9894437d0a3e6ed4afb2baa1534e1ddc22

**Comment by walseb** [comment]
Thank you!
