### ISSUE TITLE
Noweb doesn't work for system prompts

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#35]
Hello!

When running system prompts, it appears that noweb references aren't expanded.

Works:
```org
#+NAME: FOO
#+BEGIN_SRC text
bar
#+END_SRC

#+BEGIN_SRC assistant :echo t
<<FOO>>
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
(user . "bar")
#+END_EXAMPLE
```

Doesn't work:
```org
#+NAME: FOO
#+BEGIN_SRC text
bar
#+END_SRC

#+BEGIN_SRC assistant :sender system :echo t
<<FOO>>
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
(system . "<<FOO>>")
#+END_EXAMPLE
```

Thanks for any help!

**Comment by tyler-dodge** [comment]
https://github.com/tyler-dodge/org-assistant/commit/d036f82072e22a7fc985e94853deaf65c41d5967

This change should make it so that system prompts are expanded with noweb.

**Comment by walseb** [comment]
Thank you!
