### ISSUE TITLE
Org blocks aren't properly escaped

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#4]
Hello again!

It appears that the output returned by the assistant isn't being escaped so that it won't break the org block it's written in.

For instance:
```org
#+BEGIN_SRC assistant
Write back a sample org file with a single heading.
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
* My Heading

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget ante eu elit facilisis dignissim. Curabitur orci sapien, interdum ac odio vel, porttitor pulvinar lectus. Nam ullamcorper metus vitae libero blandit, vel dapibus nisi consectetur. Proin pretium dolor et velit bibendum, ut facilisis neque tincidunt. Mauris gravida quam eu ex euismod consequat. Duis bibendum cursus libero, ut ullamcorper justo placerat ac.

Ut elit elit, vestibulum id tellus id, tempus hendrerit orci. Nullam bibendum euismod lorem eu varius. Aliquam dictum semper mauris, ac aliquam justo bibendum ut. Suspendisse potenti. In hac habitasse platea dictumst. Integer euismod euismod faucibus. In hac habitasse platea dictumst. Aliquam erat volutpat. Donec quis augue nec ante bibendum maximus.

Duis vel erat mi. Vivamus vel purus id lectus suscipit sagittis. Nulla et quam sagittis, feugiat tortor vel, consequat tellus. Duis rutrum pulvinar nibh id gravida. Suspendisse potenti. Sed nec quam quis metus lobortis sodales in nec ipsum. Integer lobortis arcu a magna vestibulum pharetra. Nam dictum turpis non erat auctor ullamcorper. Suspendisse non magna ligula. Sed quis felis arcu.
#+END_EXAMPLE
```
Anything after `* My Heading` won't be inside an org-block, as the heading ends the block statement.

There should be a function that sanitizes a string for insertion into an org block.
In the case of the heading, a comma is used: `.* My Heading`

**Comment by walseb** [comment]
It appears `org-escape-code-in-string` is the function that's relevant here.

**Comment by tyler-dodge** [comment]
Thanks for that, keep the bug reports coming lol! It helps a lot getting these concise reproductions / examples of usecases that I haven't tried yet.

This should fix it: https://github.com/tyler-dodge/org-assistant/commit/8ef5232005519c4e388fb525cba52293ea533b5f

**Comment by walseb** [comment]
Thank you so much for fixing them!

I have been trying various Emacs packages for GPT, but none of them have supported session branching, reproducible sessions and running multiple jobs at the same time.
