### ISSUE TITLE
Evaluating blocks fail silently

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#5]
Hello!

Sometimes when evaluating too many blocks at the same time (perhaps around 5 concurrently), some blocks will fail and return an empty SRC block.

The result will usually look like this:

```
#+BEGIN_SRC assistant
foo
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE

#+END_EXAMPLE
```

I suspect this is due to OpenAI being rejecting requests when there are too many of them at the same time.

It would be better if an error of some sort was triggered instead, and if you could limit and queue the amount of jobs, perhaps.

I imagine this being a problem, especially if you are evaluating them all when tangling an org file.

**Comment by walseb** [comment]
OpenAI does have rate limits, so it's possible that's what's causing the empty blocks.

https://platform.openai.com/docs/guides/rate-limits/overview

**Comment by walseb** [comment]
A similar issue occurs when I lose my internet connection while it's loading. I don't receive an error. But in that case, the ID just remains in buffer.

**Comment by tyler-dodge** [comment]
Makes sense, I'll add some real error handling to it today / close this out once I push the commit.

**Comment by tyler-dodge** [comment]
This should be fully fixed as of https://github.com/tyler-dodge/org-assistant/commit/e42ff0db964d83e56f4c4226742d272b7930c3aa

Also, there's now full support for request queuing and a mode-line-format for visualizing the current state of the request queue.

**Comment by tyler-dodge** [comment]
Reopening since certain scenarios still cause a blank src block.

**Comment by tyler-dodge** [comment]
https://github.com/tyler-dodge/org-assistant/commit/99d5ba7dcb2892d222ea67baa9bf94bb4196db2e forwards the error message correctly from OpenAI.

Closing now.

**Comment by walseb** [comment]
That's incredible! 

Thank you so much! I will check it out.
