### ISSUE TITLE
Warning on latest commit

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#6]
Hi!

I get this warning whenever I call an org-assistant block on the latest commit.

```
WARNING: Callback that takes no argument may be specified. Passing callback with no argument is deprecated.
Callback must take one argument. Or, this error is coming from somewhere inside of the callback: %S
```

I don't get a backtrace. I will see if I can extract some more information later.

**Comment by tyler-dodge** [comment]
Thanks for the bug report, it should be fixed with the latest commit / reopen this if not and I'll look further
