### ISSUE TITLE
Running block multiple times quickly

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#8]
Hello again!

When running a block multiple times in quick succession, multiple results under the result tag are created:

```
#+BEGIN_SRC assistant
1+1
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
2
#+END_EXAMPLE
#+BEGIN_EXAMPLE
As an AI language model, I can give you the answer that 1+1 equals 2.
#+END_EXAMPLE
```

If I now evaluate the block again, the lower example block stays:

```
#+BEGIN_SRC assistant
1+1
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
As an AI language model, I can give you the answer that 1+1 equals 2.
#+END_EXAMPLE
#+BEGIN_EXAMPLE
As an AI language model, I can give you the answer that 1+1 equals 2.
#+END_EXAMPLE
```

While, if I had waited a bit between each invocation, it would have overridden the previous block and looked like this.

```
#+BEGIN_SRC assistant
1+1
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
As an AI language model, I can give you the answer that 1+1 equals 2.
#+END_EXAMPLE
```

I think the most logical behavior for when you run a block that's already running is to cancel the current job and start up a new job.

That would also be very useful if you have a long-running prompt that you noticed you made a mistake in while it's running.

**Comment by tyler-dodge** [comment]
Yeah, makes sense to me. The latest commit should make it work that way: https://github.com/tyler-dodge/org-assistant/commit/a623982f38a3260b9877d66f201707b700b008e2

**Comment by walseb** [comment]
That's great!

Thank you!
